name: Windows Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Formatting
      run: .\format.ps1 -Werror --dry-run

    - name: Install PkgConfig
      run: choco install pkgconfiglite --version=0.28

    - name: Install Conan
      run: pip install "conan==2.4.1"

    - name: Detect Conan Profile
      run: conan profile detect --force

    - name: Build Project
      run: .\make.ps1

    - name: Run Tests
      run: .\test.ps1
