name: Windows Conan Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Formatting Version
      run: clang-format --version

    - name: Formatting
      run: clang-format --style=Google lib/*.cpp lib/*.hpp lib/*.tpp -Werror --dry-run

    - name: Install PkgConfig
      run: choco install pkgconfiglite --version=0.28

    - name: Install Conan
      run: pip install "conan==2.4.1"

    - name: Detect Conan Profile
      run: conan profile detect --force

    - name: Build Project
      run: .\make.ps1
